id = "just-one-space"
name = "Just one space"
description = "An extension implementing a command to collapse all surrounding whitespace to just one space"
version = "0.0.1"
schema_version = 1
authors = ["matj1 <matej.bjgar@atlas.cz>"]
repository = "https://github.com/matj1/just-one-space"
